version: '3.4'

services:
  ludogameapi:
    image: ${DOCKER_REGISTRY-}ludogameapi
    build:
      context: .
      dockerfile: Dockerfile
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql-server-container_name
    hostname: mssql-server-hostname
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "#Hejsan123"
      MSSQL_PID: Express
    ports:
      - "41433:1433"
    volumes:
      - ludogameapi-data:/var/opt/mysql

 

volumes:
  ludogameapi-data:
    driver: local